# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import pet_store_pb2 as pet__store__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in pet_store_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PetStoreServiceStub(object):
    """--- Service Definition ---

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCustomers = channel.unary_unary(
                '/pet_store.PetStoreService/GetCustomers',
                request_serializer=pet__store__pb2.Empty.SerializeToString,
                response_deserializer=pet__store__pb2.CustomerListResponse.FromString,
                _registered_method=True)
        self.GetCustomer = channel.unary_unary(
                '/pet_store.PetStoreService/GetCustomer',
                request_serializer=pet__store__pb2.CustomerID.SerializeToString,
                response_deserializer=pet__store__pb2.Customer.FromString,
                _registered_method=True)
        self.CreateCustomer = channel.unary_unary(
                '/pet_store.PetStoreService/CreateCustomer',
                request_serializer=pet__store__pb2.CustomerCreateRequest.SerializeToString,
                response_deserializer=pet__store__pb2.Customer.FromString,
                _registered_method=True)
        self.UpdateCustomer = channel.unary_unary(
                '/pet_store.PetStoreService/UpdateCustomer',
                request_serializer=pet__store__pb2.CustomerUpdateRequest.SerializeToString,
                response_deserializer=pet__store__pb2.Customer.FromString,
                _registered_method=True)
        self.DeleteCustomer = channel.unary_unary(
                '/pet_store.PetStoreService/DeleteCustomer',
                request_serializer=pet__store__pb2.CustomerID.SerializeToString,
                response_deserializer=pet__store__pb2.SuccessResponse.FromString,
                _registered_method=True)
        self.GetProducts = channel.unary_unary(
                '/pet_store.PetStoreService/GetProducts',
                request_serializer=pet__store__pb2.Empty.SerializeToString,
                response_deserializer=pet__store__pb2.ProductListResponse.FromString,
                _registered_method=True)
        self.GetProduct = channel.unary_unary(
                '/pet_store.PetStoreService/GetProduct',
                request_serializer=pet__store__pb2.ProductID.SerializeToString,
                response_deserializer=pet__store__pb2.Product.FromString,
                _registered_method=True)
        self.CreateProduct = channel.unary_unary(
                '/pet_store.PetStoreService/CreateProduct',
                request_serializer=pet__store__pb2.ProductCreateRequest.SerializeToString,
                response_deserializer=pet__store__pb2.Product.FromString,
                _registered_method=True)
        self.UpdateProduct = channel.unary_unary(
                '/pet_store.PetStoreService/UpdateProduct',
                request_serializer=pet__store__pb2.ProductUpdateRequest.SerializeToString,
                response_deserializer=pet__store__pb2.Product.FromString,
                _registered_method=True)
        self.DeleteProduct = channel.unary_unary(
                '/pet_store.PetStoreService/DeleteProduct',
                request_serializer=pet__store__pb2.ProductID.SerializeToString,
                response_deserializer=pet__store__pb2.SuccessResponse.FromString,
                _registered_method=True)
        self.GetBills = channel.unary_unary(
                '/pet_store.PetStoreService/GetBills',
                request_serializer=pet__store__pb2.Empty.SerializeToString,
                response_deserializer=pet__store__pb2.BillListResponse.FromString,
                _registered_method=True)
        self.GetBill = channel.unary_unary(
                '/pet_store.PetStoreService/GetBill',
                request_serializer=pet__store__pb2.BillID.SerializeToString,
                response_deserializer=pet__store__pb2.Bill.FromString,
                _registered_method=True)
        self.CreateBill = channel.unary_unary(
                '/pet_store.PetStoreService/CreateBill',
                request_serializer=pet__store__pb2.BillCreateRequest.SerializeToString,
                response_deserializer=pet__store__pb2.Bill.FromString,
                _registered_method=True)


class PetStoreServiceServicer(object):
    """--- Service Definition ---

    """

    def GetCustomers(self, request, context):
        """Customers
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCustomer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateCustomer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateCustomer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCustomer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProducts(self, request, context):
        """Products
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBills(self, request, context):
        """Bills
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBill(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateBill(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PetStoreServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCustomers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCustomers,
                    request_deserializer=pet__store__pb2.Empty.FromString,
                    response_serializer=pet__store__pb2.CustomerListResponse.SerializeToString,
            ),
            'GetCustomer': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCustomer,
                    request_deserializer=pet__store__pb2.CustomerID.FromString,
                    response_serializer=pet__store__pb2.Customer.SerializeToString,
            ),
            'CreateCustomer': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCustomer,
                    request_deserializer=pet__store__pb2.CustomerCreateRequest.FromString,
                    response_serializer=pet__store__pb2.Customer.SerializeToString,
            ),
            'UpdateCustomer': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateCustomer,
                    request_deserializer=pet__store__pb2.CustomerUpdateRequest.FromString,
                    response_serializer=pet__store__pb2.Customer.SerializeToString,
            ),
            'DeleteCustomer': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCustomer,
                    request_deserializer=pet__store__pb2.CustomerID.FromString,
                    response_serializer=pet__store__pb2.SuccessResponse.SerializeToString,
            ),
            'GetProducts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProducts,
                    request_deserializer=pet__store__pb2.Empty.FromString,
                    response_serializer=pet__store__pb2.ProductListResponse.SerializeToString,
            ),
            'GetProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProduct,
                    request_deserializer=pet__store__pb2.ProductID.FromString,
                    response_serializer=pet__store__pb2.Product.SerializeToString,
            ),
            'CreateProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateProduct,
                    request_deserializer=pet__store__pb2.ProductCreateRequest.FromString,
                    response_serializer=pet__store__pb2.Product.SerializeToString,
            ),
            'UpdateProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateProduct,
                    request_deserializer=pet__store__pb2.ProductUpdateRequest.FromString,
                    response_serializer=pet__store__pb2.Product.SerializeToString,
            ),
            'DeleteProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteProduct,
                    request_deserializer=pet__store__pb2.ProductID.FromString,
                    response_serializer=pet__store__pb2.SuccessResponse.SerializeToString,
            ),
            'GetBills': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBills,
                    request_deserializer=pet__store__pb2.Empty.FromString,
                    response_serializer=pet__store__pb2.BillListResponse.SerializeToString,
            ),
            'GetBill': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBill,
                    request_deserializer=pet__store__pb2.BillID.FromString,
                    response_serializer=pet__store__pb2.Bill.SerializeToString,
            ),
            'CreateBill': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBill,
                    request_deserializer=pet__store__pb2.BillCreateRequest.FromString,
                    response_serializer=pet__store__pb2.Bill.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pet_store.PetStoreService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pet_store.PetStoreService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PetStoreService(object):
    """--- Service Definition ---

    """

    @staticmethod
    def GetCustomers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pet_store.PetStoreService/GetCustomers',
            pet__store__pb2.Empty.SerializeToString,
            pet__store__pb2.CustomerListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCustomer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pet_store.PetStoreService/GetCustomer',
            pet__store__pb2.CustomerID.SerializeToString,
            pet__store__pb2.Customer.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateCustomer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pet_store.PetStoreService/CreateCustomer',
            pet__store__pb2.CustomerCreateRequest.SerializeToString,
            pet__store__pb2.Customer.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateCustomer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pet_store.PetStoreService/UpdateCustomer',
            pet__store__pb2.CustomerUpdateRequest.SerializeToString,
            pet__store__pb2.Customer.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteCustomer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pet_store.PetStoreService/DeleteCustomer',
            pet__store__pb2.CustomerID.SerializeToString,
            pet__store__pb2.SuccessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProducts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pet_store.PetStoreService/GetProducts',
            pet__store__pb2.Empty.SerializeToString,
            pet__store__pb2.ProductListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pet_store.PetStoreService/GetProduct',
            pet__store__pb2.ProductID.SerializeToString,
            pet__store__pb2.Product.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pet_store.PetStoreService/CreateProduct',
            pet__store__pb2.ProductCreateRequest.SerializeToString,
            pet__store__pb2.Product.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pet_store.PetStoreService/UpdateProduct',
            pet__store__pb2.ProductUpdateRequest.SerializeToString,
            pet__store__pb2.Product.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pet_store.PetStoreService/DeleteProduct',
            pet__store__pb2.ProductID.SerializeToString,
            pet__store__pb2.SuccessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBills(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pet_store.PetStoreService/GetBills',
            pet__store__pb2.Empty.SerializeToString,
            pet__store__pb2.BillListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBill(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pet_store.PetStoreService/GetBill',
            pet__store__pb2.BillID.SerializeToString,
            pet__store__pb2.Bill.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateBill(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pet_store.PetStoreService/CreateBill',
            pet__store__pb2.BillCreateRequest.SerializeToString,
            pet__store__pb2.Bill.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
