import grpc
from concurrent import futures
import sqlite3
import os
import time
import logging

# We assume these files are generated by protoc before running
import pet_store_pb2
import pet_store_pb2_grpc

DATABASE = "../../pet_store.db"


def get_db_connection():
    db_path = os.path.join(os.path.dirname(__file__), DATABASE)
    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row
    return conn


class PetStoreServicer(pet_store_pb2_grpc.PetStoreServiceServicer):
    # --- Customers ---

    def GetCustomers(self, request, context):
        conn = get_db_connection()
        customers = conn.execute("SELECT * FROM customers").fetchall()
        conn.close()

        response = pet_store_pb2.CustomerListResponse()
        for c in customers:
            response.customers.add(
                id=c["id"],
                name=c["name"],
                email=c["email"],
                phone=c["phone"] if c["phone"] else "",
                address=c["address"] if c["address"] else "",
                created_at=c["created_at"] if c["created_at"] else "",
            )
        return response

    def GetCustomer(self, request, context):
        conn = get_db_connection()
        customer = conn.execute(
            "SELECT * FROM customers WHERE id = ?", (request.id,)
        ).fetchone()
        conn.close()

        if not customer:
            context.set_code(grpc.StatusCode.NOT_FOUND)
            context.set_details("Customer not found")
            return pet_store_pb2.Customer()

        return pet_store_pb2.Customer(
            id=customer["id"],
            name=customer["name"],
            email=customer["email"],
            phone=customer["phone"] if customer["phone"] else "",
            address=customer["address"] if customer["address"] else "",
            created_at=customer["created_at"] if customer["created_at"] else "",
        )

    def CreateCustomer(self, request, context):
        conn = get_db_connection()
        try:
            cur = conn.execute(
                "INSERT INTO customers (name, email, phone, address) VALUES (?, ?, ?, ?)",
                (request.name, request.email, request.phone, request.address),
            )
            conn.commit()
            customer_id = cur.lastrowid
            customer = conn.execute(
                "SELECT * FROM customers WHERE id = ?", (customer_id,)
            ).fetchone()
            return pet_store_pb2.Customer(
                id=customer["id"],
                name=customer["name"],
                email=customer["email"],
                phone=customer["phone"] if customer["phone"] else "",
                address=customer["address"] if customer["address"] else "",
                created_at=customer["created_at"] if customer["created_at"] else "",
            )
        except sqlite3.IntegrityError:
            context.set_code(grpc.StatusCode.ALREADY_EXISTS)
            context.set_details("Email already exists")
            return pet_store_pb2.Customer()
        finally:
            conn.close()

    def UpdateCustomer(self, request, context):
        conn = get_db_connection()
        customer = conn.execute(
            "SELECT * FROM customers WHERE id = ?", (request.id,)
        ).fetchone()
        if not customer:
            conn.close()
            context.set_code(grpc.StatusCode.NOT_FOUND)
            context.set_details("Customer not found")
            return pet_store_pb2.Customer()

        new_name = request.name if request.name else customer["name"]
        new_email = request.email if request.email else customer["email"]
        new_phone = request.phone if request.phone else customer["phone"]
        new_address = request.address if request.address else customer["address"]

        try:
            conn.execute(
                "UPDATE customers SET name = ?, email = ?, phone = ?, address = ? WHERE id = ?",
                (new_name, new_email, new_phone, new_address, request.id),
            )
            conn.commit()
            updated = conn.execute(
                "SELECT * FROM customers WHERE id = ?", (request.id,)
            ).fetchone()
            return pet_store_pb2.Customer(
                id=updated["id"],
                name=updated["name"],
                email=updated["email"],
                phone=updated["phone"] if updated["phone"] else "",
                address=updated["address"] if updated["address"] else "",
                created_at=updated["created_at"] if updated["created_at"] else "",
            )
        except sqlite3.IntegrityError:
            context.set_code(grpc.StatusCode.ALREADY_EXISTS)
            context.set_details("Email already exists")
            return pet_store_pb2.Customer()
        finally:
            conn.close()

    def DeleteCustomer(self, request, context):
        conn = get_db_connection()
        customer = conn.execute(
            "SELECT * FROM customers WHERE id = ?", (request.id,)
        ).fetchone()
        if not customer:
            conn.close()
            context.set_code(grpc.StatusCode.NOT_FOUND)
            context.set_details("Customer not found")
            return pet_store_pb2.SuccessResponse(
                success=False, message="Customer not found"
            )

        conn.execute("DELETE FROM customers WHERE id = ?", (request.id,))
        conn.commit()
        conn.close()
        return pet_store_pb2.SuccessResponse(success=True, message="Deleted")

    # --- Products ---

    def GetProducts(self, request, context):
        conn = get_db_connection()
        products = conn.execute("SELECT * FROM products").fetchall()
        conn.close()

        response = pet_store_pb2.ProductListResponse()
        for p in products:
            response.products.add(
                id=p["id"],
                name=p["name"],
                category=p["category"],
                price=float(p["price"]),
                stock=p["stock"],
                description=p["description"] if p["description"] else "",
            )
        return response

    def GetProduct(self, request, context):
        conn = get_db_connection()
        product = conn.execute(
            "SELECT * FROM products WHERE id = ?", (request.id,)
        ).fetchone()
        conn.close()

        if not product:
            context.set_code(grpc.StatusCode.NOT_FOUND)
            context.set_details("Product not found")
            return pet_store_pb2.Product()

        return pet_store_pb2.Product(
            id=product["id"],
            name=product["name"],
            category=product["category"],
            price=float(product["price"]),
            stock=product["stock"],
            description=product["description"] if product["description"] else "",
        )

    def CreateProduct(self, request, context):
        conn = get_db_connection()
        cur = conn.execute(
            "INSERT INTO products (name, category, price, stock, description) VALUES (?, ?, ?, ?, ?)",
            (
                request.name,
                request.category,
                request.price,
                request.stock,
                request.description,
            ),
        )
        conn.commit()
        p_id = cur.lastrowid
        p = conn.execute("SELECT * FROM products WHERE id = ?", (p_id,)).fetchone()
        conn.close()
        return pet_store_pb2.Product(
            id=p["id"],
            name=p["name"],
            category=p["category"],
            price=float(p["price"]),
            stock=p["stock"],
            description=p["description"] if p["description"] else "",
        )

    def UpdateProduct(self, request, context):
        conn = get_db_connection()
        product = conn.execute(
            "SELECT * FROM products WHERE id = ?", (request.id,)
        ).fetchone()
        if not product:
            conn.close()
            context.set_code(grpc.StatusCode.NOT_FOUND)
            context.set_details("Product not found")
            return pet_store_pb2.Product()

        new_name = request.name if request.name else product["name"]
        new_category = request.category if request.category else product["category"]
        new_price = request.price if request.price else product["price"]
        new_stock = request.stock if request.stock else product["stock"]
        new_description = (
            request.description if request.description else product["description"]
        )

        conn.execute(
            "UPDATE products SET name = ?, category = ?, price = ?, stock = ?, description = ? WHERE id = ?",
            (new_name, new_category, new_price, new_stock, new_description, request.id),
        )
        conn.commit()
        p = conn.execute(
            "SELECT * FROM products WHERE id = ?", (request.id,)
        ).fetchone()
        conn.close()
        return pet_store_pb2.Product(
            id=p["id"],
            name=p["name"],
            category=p["category"],
            price=float(p["price"]),
            stock=p["stock"],
            description=p["description"] if p["description"] else "",
        )

    def DeleteProduct(self, request, context):
        conn = get_db_connection()
        product = conn.execute(
            "SELECT * FROM products WHERE id = ?", (request.id,)
        ).fetchone()
        if not product:
            conn.close()
            context.set_code(grpc.StatusCode.NOT_FOUND)
            context.set_details("Product not found")
            return pet_store_pb2.SuccessResponse(
                success=False, message="Product not found"
            )

        conn.execute("DELETE FROM products WHERE id = ?", (request.id,))
        conn.commit()
        conn.close()
        return pet_store_pb2.SuccessResponse(success=True, message="Deleted")

    # --- Bills ---

    def GetBills(self, request, context):
        conn = get_db_connection()
        bills = conn.execute("SELECT * FROM bills").fetchall()

        response = pet_store_pb2.BillListResponse()
        for b in bills:
            bill_msg = response.bills.add()
            bill_msg.id = b["id"]
            bill_msg.customer_id = b["customer_id"]
            bill_msg.date = b["date"]
            bill_msg.total_amount = float(b["total_amount"])

            items = conn.execute(
                """
                SELECT bi.*, p.name as product_name 
                FROM bill_items bi
                JOIN products p ON bi.product_id = p.id
                WHERE bi.bill_id = ?
            """,
                (b["id"],),
            ).fetchall()

            for item in items:
                item_msg = bill_msg.items.add()
                item_msg.product_id = item["product_id"]
                item_msg.quantity = item["quantity"]
                item_msg.unit_price = float(item["unit_price"])
                item_msg.subtotal = float(item["subtotal"])
                item_msg.product_name = item["product_name"]

        conn.close()
        return response

    def GetBill(self, request, context):
        conn = get_db_connection()
        b = conn.execute("SELECT * FROM bills WHERE id = ?", (request.id,)).fetchone()

        if not b:
            conn.close()
            context.set_code(grpc.StatusCode.NOT_FOUND)
            context.set_details("Bill not found")
            return pet_store_pb2.Bill()

        bill_msg = pet_store_pb2.Bill(
            id=b["id"],
            customer_id=b["customer_id"],
            date=b["date"],
            total_amount=float(b["total_amount"]),
        )

        items = conn.execute(
            """
            SELECT bi.*, p.name as product_name 
            FROM bill_items bi
            JOIN products p ON bi.product_id = p.id
            WHERE bi.bill_id = ?
        """,
            (b["id"],),
        ).fetchall()

        for item in items:
            item_msg = bill_msg.items.add()
            item_msg.product_id = item["product_id"]
            item_msg.quantity = item["quantity"]
            item_msg.unit_price = float(item["unit_price"])
            item_msg.subtotal = float(item["subtotal"])
            item_msg.product_name = item["product_name"]

        conn.close()
        return bill_msg

    def CreateBill(self, request, context):
        if not request.items:
            context.set_code(grpc.StatusCode.INVALID_ARGUMENT)
            context.set_details("Bill must have at least one item")
            return pet_store_pb2.Bill()

        conn = get_db_connection()
        try:
            total_amount = 0
            bill_items_data = []

            for item in request.items:
                product_row = conn.execute(
                    "SELECT price FROM products WHERE id = ?", (item.product_id,)
                ).fetchone()
                if not product_row:
                    context.set_code(grpc.StatusCode.INVALID_ARGUMENT)
                    context.set_details(f"Product {item.product_id} not found")
                    return pet_store_pb2.Bill()

                price = product_row["price"]
                subtotal = price * item.quantity
                total_amount += subtotal
                bill_items_data.append(
                    (item.product_id, item.quantity, price, subtotal)
                )

            # Create Bill
            cur = conn.execute(
                "INSERT INTO bills (customer_id, total_amount) VALUES (?, ?)",
                (request.customer_id, float(total_amount)),
            )
            bill_id = cur.lastrowid

            # Create Bill Items
            for data in bill_items_data:
                conn.execute(
                    "INSERT INTO bill_items (bill_id, product_id, quantity, unit_price, subtotal) VALUES (?, ?, ?, ?, ?)",
                    (bill_id, data[0], data[1], float(data[2]), float(data[3])),
                )

            conn.commit()

            # Retrieve the created bill
            b = conn.execute("SELECT * FROM bills WHERE id = ?", (bill_id,)).fetchone()
            bill_msg = pet_store_pb2.Bill(
                id=b["id"],
                customer_id=b["customer_id"],
                date=b["date"],
                total_amount=float(b["total_amount"]),
            )

            items = conn.execute(
                """
                SELECT bi.*, p.name as product_name 
                FROM bill_items bi
                JOIN products p ON bi.product_id = p.id
                WHERE bi.bill_id = ?
            """,
                (b["id"],),
            ).fetchall()

            for item in items:
                item_msg = bill_msg.items.add()
                item_msg.product_id = item["product_id"]
                item_msg.quantity = item["quantity"]
                item_msg.unit_price = float(item["unit_price"])
                item_msg.subtotal = float(item["subtotal"])
                item_msg.product_name = item["product_name"]

            return bill_msg

        except Exception as e:
            conn.rollback()
            context.set_code(grpc.StatusCode.INTERNAL)
            context.set_details(str(e))
            return pet_store_pb2.Bill()
        finally:
            conn.close()


def serve():
    # Configure logging
    logging.basicConfig(level=logging.INFO)
    logger = logging.getLogger(__name__)

    # Create a gRPC server
    server = grpc.server(futures.ThreadPoolExecutor(max_workers=10))

    # Add the servicer class to the server
    pet_store_pb2_grpc.add_PetStoreServiceServicer_to_server(PetStoreServicer(), server)

    # Listen on port 5002
    port = "5002"
    server.add_insecure_port(f"[::]:{port}")
    server.start()
    logger.info(f"gRPC Server listening on port {port}...")

    try:
        # Prevent the main thread from exiting
        while True:
            time.sleep(86400)
    except KeyboardInterrupt:
        server.stop(0)
        logger.info("Server stopped.")


if __name__ == "__main__":
    serve()
